NAME = NoahIovanniLorenzoDíaz-Práctica1.tar.gz

all:
	g++ -g numbere.cc -o numbere

git: 
	git pull
	git add .
	git commit -m "Changes"
	git push

tar:
	tar cfvz $(NAME) .

clean:
	rm *.exe *.out *tar.gz